CREATE TABLE IF NOT EXISTS HF_CRPW (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_USER bigint UNIQUE KEY NOT NULL,
	PSWD varchar(256) NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
	FOREIGN KEY(ID_USER) REFERENCES HF_REGUSER(ID)
);
