CREATE TABLE IF NOT EXISTS HF_ADDRESS (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_USER bigint UNIQUE KEY NOT NULL,
   	FULL_NAME varchar(200) NOT NULL,
	STREET varchar(300) NOT NULL,
	POSTAL_CODE varchar(100) NOT NULL,
	CITY varchar(200) NOT NULL,
	PROVINCE varchar(100) NOT NULL,
	ADDITIONAL_INFO varchar(400) DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_USER) REFERENCES HF_REGUSER(ID)
);
