CREATE TABLE IF NOT EXISTS HF_PERMIT (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_APP bigint NOT NULL,
    CODE varchar(200) NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
    FOREIGN KEY(ID_APP) REFERENCES HF_APP(ID)
);
