export enum AppPermit {
    APP_CAN_AUTH = 'APP_CAN_AUTH',
    APP_CAN_CREATE = 'APP_CAN_CREATE',

    TOKEN_CAN_READ = 'TOKEN_CAN_READ',
    TOKEN_CAN_WRITE = 'TOKEN_CAN_WRITE',

    TOKEN_CAN_READ_ALL = 'TOKEN_CAN_READ_ALL',
    TOKEN_CAN_WRITE_ALL = 'TOKEN_CAN_WRITE_ALL',
}